export const SET_BOOKS = 'SET_BOOKS';
export const SET_BOOKS_TO_SHOW = 'SET_BOOKS_TO_SHOW';
export const SET_BOOK_GENRE = 'SET_BOOK_GENRE';

export const SET_IS_PRELOADER_SHOW = 'SET_IS_PRELOADER_SHOW';
export const SET_IS_MOBILE_HEADER_POPUP_OPEN = 'SET_IS_MOBILE_HEADER_POPUP_OPEN';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_IS_LOGGED_IN = 'SET_IS_LOGGED_IN';
